apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow-argocd
data:
  airflow.cfg: |
    [core]
    dags_folder = /opt/airflow/dags-source/current/dags
    base_log_folder = /opt/airflow/logs
    load_examples = False
    unit_test_mode = False
    load_default_connections = False
    execute_tasks_new_python_subprocess = False
    executor = CeleryExecutor
    parallelism = 4
    max_active_tasks_per_dag = 2
    fernet_key = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0=
    auth_manager = airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

    [database]
    sql_alchemy_conn = postgresql://airflow:airflow_dev_password@airflow-postgres:5432/airflow
    sql_alchemy_pool_enabled = true
    sql_alchemy_pool_size = 5
    sql_alchemy_pool_recycle = 3600

    [celery]
    broker_url = redis://airflow-redis:6379/0
    result_backend = db+postgresql://airflow:airflow_dev_password@airflow-postgres:5432/airflow
    worker_concurrency = 4

    [api]
    secret_key = dev-api-secret-key-change-me-in-prod
    auth_jwt_secret = dev-jwt-secret-change-me-in-prod
    expose_config = False

    [fab]
    auth_backends = airflow.providers.fab.auth_manager.api.auth.backend.session
