# WARNING: secret en clair pour TEST uniquement.
# En prod : utiliser SealedSecrets, ExternalSecrets, ou Vault.
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-credentials
  namespace: airflow-argocd
type: Opaque
stringData:
  username: oauth2
  token: glpat-22Lbx0P7_HohA8WfK1h6kW86MQp1OjNjCA.01.0y1u2rmyr
